config/routes.rb
Rails.application.routes.draw do

  root 'movies#index'

  resources :movies
  

  
  get 'similar/:title',to: 'movies#similar', as: :similar
end

app/models/movie.rb
class Movie < ActiveRecord::Base
    def self.all_ratings()
        # Get ratings that are present in movie list and return them
        # looked at https://blog.toshima.ru/2018/08/04/activerecord-distinct-pluck.html to learn how to extract all unique values of rating
        return Movie.distinct.pluck(:rating).sort
    end
    
    def self.with_ratings(ratings_list)
    # if ratings_list is an array such as ['G', 'PG', 'R'], retrieve all
    #  movies with those ratings
    # if ratings_list is nil, retrieve ALL movies
        if ratings_list.nil? or ratings_list.empty?
            return Movie.all
        end

        return Movie.where(rating: ratings_list)
    end
    
    def self.find_similar(title)
        director = Movie.find_by_title(title).director
        return nil if director.nil? or director.empty?
        return Movie.where(:director => director).pluck(:title)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

  def show
    id = params[:id] # retrieve movie ID from URI route
    @movie = Movie.find(id) # look up movie by unique ID
    # will render app/views/movies/show.<extension> by default
  end

  def index
    # Session
    # Only have this path when you first enter the index page
    # Otherwise, it is /movies when you go back to index
    if request.path == '/'
      reset_session
    end
    
    # added to make this testable
    @session_sort = session[:sort_by]
    @session_ratings = session[:ratings_to_show]
    
    # "Remember"/refill form inputs using session
    @ratings_to_show = !@session_ratings.nil? ? @session_ratings : []

    if !@session_sort.nil?
      # if the sort by value changed, account for that
      if !params[:sort].nil? and params[:sort] != @session_sort
        @session_sort = params[:sort]
      end
      @sort = @session_sort
    else
      @sort = params[:sort] 
    end
    
    # Set session values
    @session_sort = @sort
    
    if !params[:ratings].nil?
      @ratings_to_show = params[:ratings].keys
      @session_ratings = @ratings_to_show
    end
    
    # Define what will be shown in the view
    @movies = Movie.with_ratings(@ratings_to_show)
    @all_ratings = Movie.all_ratings


    # bg-warning is the Bootstrap class
    # hilite is a CSS class that sets the color back to normal if we aren't sorting by it
    if @sort
      @movies = @movies.order(@sort) 
        case @sort
        when "title"
          @title_header = 'bg-warning'
          @release_date_header = 'hilite'
        when "release_date"
          @release_date_header = 'bg-warning'
          @title_header = 'hilite'
        end
    end
    
  end

  def new
    # default: render 'new' template
  end

  def create
    @movie = Movie.create!(movie_params)
    flash[:notice] = "#{@movie.title} was successfully created."
    redirect_to movies_path
  end

  def edit
    @movie = Movie.find params[:id]
  end

  def update
    @movie = Movie.find params[:id]
    @movie.update_attributes!(movie_params)
    flash[:notice] = "#{@movie.title} was successfully updated."
    redirect_to movie_path(@movie)
  end

  def destroy
    @movie = Movie.find(params[:id])
    @movie.destroy
    flash[:notice] = "Movie '#{@movie.title}' deleted."
    redirect_to movies_path
  end
  
  def similar
    @find_similar = Movie.find_similar(params[:title])
    if @find_similar.nil?
      redirect_to movies_path
      flash[:warning] = "'#{params[:title]}' has no director info"
    end
    @movie = Movie.find_by_title([params[:title]])
  end

  private
  # Making "internal" methods private is not required, but is a common practice.
  # This helps make clear which methods respond to requests, and which ones do not.
  def movie_params
    params.require(:movie).permit(:title, :rating, :description, :release_date, :director)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
  # Checks if a number is odd:
  def oddness(count)
    count.odd? ?  "odd" :  "even"
  end
end

app/views/layouts/_flash.erb
<% if flash[:notice] %>
  <div class="alert alert-info" role="alert" id="notice">
    <%= flash[:notice] %>
  </div>
<% elsif flash[:warning] %>
  <div class="alert alert-danger" role="alert" id="warning">
    <%= flash[:warning] %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<%# Our "base" layout should be a valid HTML document. %>
<!DOCTYPE html>
<html>
  <head>
    <title>Rotten Potatoes!</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', 'media' => 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%# These classes come from the Bootstrap CSS framework. %>
    <nav class="navbar navbar-expand-lg bg-primary text-white mb-3">
      <h1 class="title">Rotten Potatoes!</h1>
    </nav>
    <div class="container">
      <%# Render "flash" messages in our application. This loads _flash.erb %>
      <%= render 'layouts/flash' %>
      <main id="main">
        <%= yield %>
      </main>
    </div>
  </body>
</html>

app/views/movies/edit.html.erb
<h2>Edit Existing Movie</h2>
<%= form_tag movie_path(@movie), :method => :put do %>
  <%= label :movie, :title, 'Title', :class => 'col-form-label' %>
  <%= text_field :movie, 'title', :class => 'form-control' %>
  <%= label :movie, :rating, 'Rating', :class => 'col-form-label'  %>
  <%= select :movie, :rating, ['G','PG','PG-13','R','NC-17'], {}, {:class => 'form-control col-1'} %>
  <%= label :movie, :release_date, 'Released On', :class => 'col-form-label'  %>
  <%= date_select :movie, :release_date, {}, :class => 'form-control col-2 d-inline' %>
  <br/>
  <%= label :movie, :director, 'Director', :class => 'col-form-label' %>
  <%= text_field :movie, 'director', :class => 'form-control' %>
  <br/>
  <%= submit_tag 'Update Movie Info', :class => 'btn btn-primary' %>
  <%= link_to 'Cancel', movies_path, :class => 'btn btn-secondary' %>
<% end %>

app/views/movies/index.html.erb
<!--  This file is app/views/movies/index.html.erb -->
<h2>All Movies</h2>

<%#  Part 2: Start here... %>
<%= form_tag movies_path, method: :get, id: 'ratings_form' do %>
  Include:
  <% @all_ratings.each do |rating| %>
    <div class="form-check  form-check-inline">
      <%= label_tag "ratings[#{rating}]", rating, class: 'form-check-label' %>
      <%= check_box_tag "ratings[#{rating}]", "1",  @ratings_to_show.include?(rating), class: 'form-check-input' %>
    </div>
  <% end %>
  <%= hidden_field_tag "sort", @sort %>
  <%= submit_tag 'Refresh', id: 'ratings_submit', class: 'btn btn-primary' %>
<% end %>

<table class="table table-striped col-md-12" id="movies">
  <thead>
    <tr>
      <th class="<%=@title_header%>">
        <%= link_to "Movie Title", movies_path({:sort => 'title', :ratings => Hash[@ratings_to_show.collect {|item| [item, "1"]}]}), :id => 'title_header' %>
      </th>
      <th>Rating</th>
      <th class="<%=@release_date_header%>">
        <%= link_to "Release Date", movies_path({:sort => 'release_date', :ratings => Hash[@ratings_to_show.collect {|item| [item, "1"]}]}), :id => 'release_date_header' %>
      </th>
      <th>Director</th>
      <th>More Info</th>
    </tr>
  </thead>
  <tbody>
    <% @movies.each do |movie| %>
      <tr>
        <td>
          <%= movie.title %>
        </td>
        <td>
          <%= movie.rating %>
        </td>
        <td>
          <%= movie.release_date %>
        </td>
        <td>
          <%= movie.director %>
        </td>
        <td>
          <%= link_to "More about #{movie.title}", movie_path(movie) %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'Add new movie', new_movie_path, :class => 'btn btn-primary' %>

app/views/movies/new.html.erb
<h2>Create New Movie</h2>

<%= form_tag movies_path, :class => 'form' do %>
  <%= label :movie, :title, 'Title', :class => 'col-form-label' %>
  <%= text_field :movie, :title, :class => 'form-control' %>
  <%= label :movie, :rating, 'Rating', :class => 'col-form-label'  %>
  <%= select :movie, :rating, ['G','PG','PG-13','R','NC-17'], {}, {:class => 'form-control col-1'} %>
  <%= label :movie, :release_date, 'Released On', :class => 'col-form-label'  %>
  <%= date_select :movie, :release_date, {}, :class => 'form-control col-2 d-inline' %>
  <%= label :movie, :director, 'Director', :class => 'col-form-label' %>
  <%= text_field :movie, :director, :class => 'form-control' %>
  <br/>
  <%= submit_tag 'Save Changes', :class => 'btn btn-primary' %>
  <%= link_to 'Cancel', movies_path, :class => 'btn btn-secondary' %>
<% end %>

app/views/movies/show.html.erb
<!--  app/views/movies/show.html.erb -->
<h2>Details about <em><%= @movie.title %></em></h2>

<ul id="details">
  <li>
    Rating:
    <%= @movie.rating %>
  </li>
  <li>
    Released on:
    <%= @movie.release_date.strftime("%B %d, %Y") %>
  </li>
  <li>
    Director:
    <%= @movie.director %>
  </li>
</ul>

<h3>Description:</h3>
<p id="description">
  <%= @movie.description %>
</p>

<div class="row">
  <%= link_to 'Find Movies With Same Director', similar_path(@movie.title), :class => 'btn btn-primary col-2' %>
  <%= link_to 'Edit', edit_movie_path(@movie), :class => 'btn btn-primary col-2' %>
  <%= link_to 'Delete', movie_path(@movie), 'data-method' => 'delete', 'data-confirm' => 'Are you sure?', :class => 'btn btn-danger col-2' %>
  <%= link_to 'Back to movie list', movies_path, :class => 'btn btn-primary col-2' %>
</div>

app/views/movies/similar.html.erb
<h2>Similar Movies for <%= @movie.title %></h2>
 <ul>
    <% @find_similar.each do |title| %>
      <li> <%= title %></li>
    <% end %>
</ul>
<%= link_to 'Back', movies_path, :class => 'btn btn-secondary' %>